#!/usr/bin/env python3
"""Render canonical typed config into the legacy runtime .conf format.

Only typed fields are rendered. Secret references remain references and their contents
are never read. Public listeners are rejected unless explicitly allowed by policy.
"""
from __future__ import annotations

import json
import shlex
import sys
from pathlib import Path
from typing import Any


PUBLIC_BINDS = {"0.0.0.0", "::"}
SUPPORTED_BACKENDS = {"ssh-socks", "local-endpoint", "sing-box", "mihomo", "http-connect"}


def require(obj: dict[str, Any], key: str, path: str) -> Any:
    if key not in obj:
        raise ValueError(f"missing required field: {path}.{key}")
    return obj[key]


def assignment(name: str, value: Any) -> str:
    if isinstance(value, bool):
        rendered = "true" if value else "false"
        return f'{name}="{rendered}"'
    return f"{name}={shlex.quote(str(value))}"


def validate(config: dict[str, Any]) -> None:
    if config.get("schema_version") != 1:
        raise ValueError("schema_version must be 1")
    for section in ("backend", "listeners", "health", "integrations", "routing", "security"):
        if not isinstance(config.get(section), dict):
            raise ValueError(f"{section} must be an object")
    backend = config["backend"]
    backend_type = require(backend, "type", "backend")
    if backend_type not in SUPPORTED_BACKENDS:
        raise ValueError(f"unsupported backend: {backend_type}")
    listeners = config["listeners"]
    socks = require(listeners, "socks5", "listeners")
    if not isinstance(socks, dict):
        raise ValueError("listeners.socks5 must be an object")
    http = listeners.get("http", {"enabled": False, "bind": "127.0.0.1", "port": 8118})
    for name, listener in (("socks5", socks), ("http", http)):
        if listener.get("bind") in PUBLIC_BINDS and name == "socks5":
            raise ValueError("public SOCKS listener requires explicit deployment policy")
        if name == "http" and listener.get("enabled") and listener.get("bind") in PUBLIC_BINDS:
            raise ValueError("public HTTP listener requires explicit deployment policy")
    if config["security"].get("allow_public_listener") is True and (
        socks.get("bind") in PUBLIC_BINDS or (http.get("enabled") and http.get("bind") in PUBLIC_BINDS)
    ):
        raise ValueError("authenticated public deployment policy is not implemented by the legacy runtime")


def build(config: dict[str, Any]) -> str:
    validate(config)
    backend = config["backend"]
    options = backend.get("options", {})
    listeners = config["listeners"]
    socks = listeners["socks5"]
    http = listeners.get("http", {})
    routing = config["routing"]
    health = config["health"]
    integrations = config["integrations"]
    security = config["security"]

    lines = ["# Generated by proxy-agent from canonical typed config", assignment("BACKEND", backend["type"])]
    if backend["type"] == "ssh-socks":
        mapping = {
            "REMOTE_HOST": options.get("remote_host", ""),
            "REMOTE_USER": options.get("remote_user", ""),
            "REMOTE_PORT": options.get("remote_port", 22),
            "REMOTE_SSH_KEY": options.get("remote_ssh_key_ref", ""),
            "AUTOSSH_MONITOR_PORT": options.get("autossh_monitor_port", 0),
            "SSH_SERVER_ALIVE_INTERVAL": options.get("ssh_server_alive_interval", 30),
            "SSH_SERVER_ALIVE_COUNT_MAX": options.get("ssh_server_alive_count_max", 3),
            "SSH_STRICT_HOST_KEY_CHECKING": options.get("ssh_strict_host_key_checking", security.get("ssh_host_key_checking", "yes")),
            "SSH_KNOWN_HOSTS": options.get("ssh_known_hosts_ref", "~/.ssh/known_hosts"),
        }
    elif backend["type"] == "local-endpoint":
        mapping = {"LOCAL_PROXY_URL": options.get("proxy_url", ""), "LOCAL_PROXY_STATUS_TARGET": options.get("status_target", "")}
    elif backend["type"] == "sing-box":
        mapping = {"SING_BOX_CONFIG": options.get("config_path", ""), "SING_BOX_BIN": options.get("binary", "sing-box")}
    elif backend["type"] == "mihomo":
        mapping = {"MIHOMO_CONFIG": options.get("config_path", ""), "MIHOMO_BIN": options.get("binary", "mihomo")}
    else:
        mapping = {"HTTP_CONNECT_PROXY_URL": options.get("proxy_url", "")}
    lines.extend(assignment(k, v) for k, v in mapping.items())
    lines.extend([
        assignment("SOCKS_BIND", socks["bind"]), assignment("SOCKS_PORT", socks["port"]),
        assignment("HTTP_ENABLED", http.get("enabled", False)), assignment("HTTP_BIND", http.get("bind", "127.0.0.1")),
        assignment("HTTP_PORT", http.get("port", 8118)), assignment("SSH_STRICT_HOST_KEY_CHECKING", security.get("ssh_host_key_checking", "yes")),
    ])
    lines.extend([
        assignment("DIRECT_CIDRS", ",".join(routing.get("direct_cidrs", []))),
        assignment("DIRECT_DOMAINS", ",".join(routing.get("direct_domains", []))),
        assignment("NO_PROXY_EXTRA", ",".join(routing.get("no_proxy_extra", []))),
    ])
    rules = routing.get("rules", [])
    legacy_rules = []
    for rule in sorted(rules, key=lambda x: (x["priority"], x["action"], x["matcher"], x["pattern"])):
        legacy_rules.append(f'{rule["priority"]}|{rule["action"].upper()}|{rule["matcher"]}|{rule["pattern"]}')
    lines.append(assignment("ROUTE_RULES", "\n".join(legacy_rules)))
    lines.extend([
        assignment("HEALTH_TARGETS", ",".join(health.get("targets", []))), assignment("HEALTH_NETWORK_REQUIRED", health["network_required"]),
        assignment("HEALTH_TIMEOUT", health["timeout"]), assignment("HEALTH_RETRIES", health["retries"]),
        assignment("HEALTH_BACKOFF", health["backoff"]), assignment("HEALTH_AUTO_RECOVER", health["auto_recover"]),
        assignment("INTEGRATE_GIT", integrations["git"]), assignment("INTEGRATE_DOCKER", integrations["docker"]),
        assignment("INTEGRATE_PIP", integrations["pip"]), assignment("INTEGRATE_NPM", integrations["npm"]),
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        config = json.load(sys.stdin)
        if not isinstance(config, dict):
            raise ValueError("typed config must be a JSON object")
        sys.stdout.write(build(config))
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"typed legacy export: ERROR: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
